config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'carts/create'
  # get 'carts/show'
  # get 'dashboard/show'
  # get 'products/show'
  # get 'products/new'
  # get 'products/edit'
  # get 'products/update'
  # get 'products/create'
  # get 'projects/index'
  # get 'projects/new'
  # get 'projects/edit'
  # get 'projects/create'
  # get 'projects/update'
  # get 'projects/show'

  devise_for :users
  post 'create_playlist', to: 'dashboards#create_playlist'
  get '/auth/spotify/callback', to: 'dashboards#create_playlist'
  root to: 'pages#home'
  resources :projects, only: [:index, :show, :edit, :new, :create, :update] do
    resources :products, only: [:show, :new, :create]
    resources :transactions, only: [:new,:show, :create]
  end
  resource :dashboard, only: [:show]
  resources :carts, only: [:show, :create]
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success">
    <strong><%= notice %></strong>
  </div>
<% end %>


<% if alert %>
  <div class="alert alert-warning ">
    <strong><%= alert %></strong>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class="footer-left">
    <p>Get Yo’ Shares is the first crowdfunding platform to finance artist’s projects.</p>
    <div class="footer-social-media">
      <a href=""><i class="fab fa-spotify"></i></a>
      <a href=""><i class="fab fa-facebook"></i></a>
      <a href=""><i class="fab fa-twitter"></i></a>
    </div>
  </div>

  <div class="footer-right">
    <ul>
      <li><a href="">About us</a></li>
      <li><a href="">Contact</a></li>
      <li><a href="">FAQs</a></li>
      <li><a href="">Privacy</a></li>
      <li><a href="">Terms of service</a></li>
      <li><a href="">Cookie Policy</a></li>
    </ul>
  </div>

</footer>

app/views/shared/_navbar-home.html.erb
<div class="navbar navbar-expand-sm navbar-gys mb-3">
  <div class="container-navbar">
    <%= link_to "GET YO' SHARES", root_path, class: "logo"%>

    <a class="navbar-toggler" type="text" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </a>

    <div class="collapse navbar-collapse navbar-collapse-gys" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto navbar-menu">
          <li class="nav-link"><i class="fa fa-compass"></i><%= link_to "Explore", projects_path %></li>
          <li class="nav-link"><i class="fa fa-chart-line"></i></i><%= link_to "Dashboard", dashboard_path%></li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key != nil %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <div data-initials="FH" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></div>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav me-auto">
          <li class="nav-link"><i class="fa fa-sign-in-alt"></i><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
          <li class="nav-link"><i class="fa fa-user-plus"></i><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar bg-white">
  <div class="sidebar-home">
    <%= link_to image_tag('https://cdn2.iconfinder.com/data/icons/music-filled-pixel-perfect/64/music-35-512.png'), root_path, class: "logo" %>
    <p>Get Yo' Shares</p>
  </div>
  <hr>
  <% if user_signed_in? %>
  <div class="sidebar-menu">
    <ul>
      <li>Menu</li>
      <li class="nav-link"><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
      <li class="nav-link"><i class="fa fa-compass"></i><%= link_to "Explore", projects_path %></li>
      <li class="nav-link"><i class="fa fa-chart-line"></i></i><%= link_to "Dashboard", dashboard_path%></li>
      <li class="nav-link"><i class="fa fa-times-circle"></i><%= link_to "Log out", destroy_user_session_path,method: :delete%></li>
    </ul>
  </div>
  <div class="sidebar-profile">
    <%= cl_image_tag current_user.photo.key, class: "avatar"%>
    <%= current_user.first_name %>
  </div>
  <% else %>
    <div class="sidebar-menu">
      <ul>
        <li class="nav-link"><i class="fa fa-sign-in-alt"></i><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
        <li class="nav-link"><i class="fa fa-user-plus"></i><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
        </ul>
    </div>
    <% end %>
</div>