config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'carts/create'
  # get 'carts/show'
  # get 'dashboard/show'
  # get 'products/show'
  # get 'products/new'
  # get 'products/edit'
  # get 'products/update'
  # get 'products/create'
  # get 'projects/index'
  # get 'projects/new'
  # get 'projects/edit'
  # get 'projects/create'
  # get 'projects/update'
  # get 'projects/show'

  devise_for :users
  post 'create_playlist', to: 'dashboards#create_playlist'
  get '/auth/spotify/callback', to: 'dashboards#create_playlist'
  root to: 'pages#home'
  resources :projects, only: [:index, :show, :edit, :new, :create, :update] do
    resources :products, only: [:show, :new, :create]
    resources :transactions, only: [:new,:show, :create]
  end
  resource :dashboard, only: [:show]
  resources :carts, only: [:show, :create]
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  include Abyme::Model
  belongs_to :user
  has_many :products, dependent: :destroy, inverse_of: :project
  has_many :revenues
  has_many :tokens, dependent: :destroy, inverse_of: :project
  has_one_attached :photo
  has_many :transactions, through: :tokens
  has_many :tracks, through: :products
  abymize :products
  abymize :tokens


  def unit_price
    tokens.first.price
  end

  def number_of_transactions(project)
    transactions.where(token_id: Token.where(project_id: project.id)).count
  end

  def total_amount_invested(project)
    unit_price * number_of_transactions(project).to_i
  end

  def total_amount_available(project)
    project.number_of_tokens * unit_price
  end

  def number_of_buyers(project)
    buyers = transactions.where(token_id: Token.where(project_id: project.id)).group(:user_id).count
    if buyers.values.count == 0
      0
    else
      buyers.values.count
    end
  end

  def project_revenue(project)
    if revenues.find_by(project_id: project) != nil
      revenues.find_by(project_id: project).revenue
    else
      0
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show]

  def index
    @projects = policy_scope(Project)
    # we search by genre or artist name
    if params[:query].present?
      sql_query = " \
      products.genre ILIKE :query \
      OR users.artist_name ILIKE :query \
    "
      @projects = Project.joins(:products, :user).where(sql_query, query: "%#{params[:query]}%").distinct
    else
      @projects = Project.all
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    if @project.save!
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
    authorize @project
  end

  def update
  end

  def show
    authorize @project
    # variables for piechart n°1
    distribution_share = @project.average_distribution_share
    investor_share = @project.number_of_tokens
    artist_share = 100 - distribution_share - investor_share
    @shares = { "Distributor's share": distribution_share, "Investor's share": investor_share, "Artist's share": artist_share }

    @cart = current_user.carts.new
  end

  def project_params
    params.require(:project).permit(
      abyme_attributes, :id, :user_id, :name, :description, :distributor, :release_date, :average_distribution_share,
      :expected_audio_streams_year, :expected_video_streams_year, :number_of_tokens, :photo,
      tokens_attributes: [:price_cents],
      products_attributes: [
        :id, :genre, :spotify_id, :description, :_destroy, tracks_attributes: [
          :id, :title, :youtube_id, :_destroy
        ]
      ]
    )
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<div class="container-index">
  <div class="project-title">
  <h1 class="text-primary my-5">All <span class="banner-highlight-primary">projects</span></h1>
  </div>

<%# change artist_name to modify the whole card %>
  <% user = User.find_by(artist_name: "Cardi B") %>
  <% project = Project.find_by(user_id: user) %>
  <div class="index-artist-banner text-white shadow-sm p-3 mb-5 rounded">
    <div class="index-artist-banner-card-img-overlay">
      <h1 class="card-title"> <%= project.name %> </h1>
      <h5 class="card-text"> <%=  user.artist_name %> </h5>
      <div class="index-artist-card-tokens-infos">
        <p class="card-text"><i class="fas fa-donate"></i> <%= project.number_of_transactions(project) != nil ? (project.number_of_tokens - project.number_of_transactions(project)) : project.number_of_tokens %> Tokens left </p>
        <p class="card-text"><i class="fas fa-user-friends"></i> <%= pluralize project.number_of_buyers(project), 'Buyer' %></p>
      </div>
      <%= link_to "Discover", project_path(project.id), class: 'index-artist-banner-btn'%>
    </div>

    <div class="index-cardi-absolute"></div>
  </div>

<%# End of banner-card %>

  <div class="row row-cols-auto d-flex justify-content-between index-cards">
    <% @projects.each do |project| %>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="index-cards-card text-white shadow-sm mb-5 rounded p-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path User.find(project.user_id).photo.key, crop: :fit, height: 320 %>'); background-repeat:no-repeat; background-size:cover; background-position:inherit; height:240px;">
          <div class="index-card-img-overlay">
          <div class="index-cards-card-project-info">
            <h5 class="card-title"> <%= project.name %></h5>
            <p class="card-text"> <%= project.user.artist_name  %> </p>
          </div>
          <div class="index-cards-card-bottom">
            <div class="index-cards-card-tokens-info">
              <p class="card-text"><i class="fas fa-donate"></i> <%= project.number_of_transactions(project) != nil ? (project.number_of_tokens - project.number_of_transactions(project)) : project.number_of_tokens %> Tokens left </p>
              <p class="card-text"><i class="fas fa-user-friends"></i> <%= pluralize project.number_of_buyers(project), 'Buyer' %></p>
            </div>
            <%= link_to "Discover", project_path(project) ,  class: 'btn btn-outline-light'%>
          </div>
          </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/projects/new.html.erb
<div class="container-gys">
  <div class="p-4 bg-white">
    <%= simple_form_for @project do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :average_distribution_share %>
      <%= f.input :expected_audio_streams_year %>
      <%= f.input :expected_video_streams_year %>
      <%= f.input :release_date %>
      <%= f.input :distributor %>
      <%= f.input :photo, as: :file %>
      <%= f.input :number_of_tokens %>

      <%= f.abyme_for(:tokens)%>

      <%= f.abyme_for(:products) do |abyme| %>
        <%= abyme.records %>
        <%= abyme.new_records %>
        <%= add_associated_record %>
      <% end %>
      <%= f.submit 'Save new project', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<!-- banner -->
<div class="container-gys">

  <div class="artist-banner-show mb-3 rounded" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @project.photo.key %>');">
    <div class="artist-banner-name-show">
      <h3><%= User.find(@project.user_id).artist_name.capitalize %></h3>
      <p><%= @project.name  %></p>
    </div>
    <div class="artist-banner-genre-show">
      <p><%= Product.find_by(project_id: @project.id).genre %></p>
    </div>
    <div class="artist-banner-token-show">
      <p><%= @project.number_of_tokens - @project.number_of_transactions(@project)%></p>
      <p>tokens left</p>
    </div>
  </div>
</div>


<div class="container-gys">
  <!-- project information -->
  <div class="artist-project-info">
    <div class="row">
      <!-- project description & music player: left part -->
      <div class="col-8 p-2">
        <p class="opacity-75 p-2 col-lg-11 col-sm-12"><%= @project.description %></p>

        <div class="project-show-media justify-content-between">
          <!-- spotify infos -->
          <div class="col-lg-11 col-sm-12">
            <% @spotify_id = @project.products.first%>
            <iframe src="https://open.spotify.com/embed/album/<%=@spotify_id.spotify_id%>" width="100%" height="350px "
            frameborder="0" allowtransparency="true" allow="encrypted-media" style="border-radius:8px"></iframe>
          </div>

          <!-- youtube infos, video is launched automatically but muted -->
          <div class="col-lg-11 col-sm-12">

            <% @youtube_id = @project.tracks.where.not(youtube_id: nil).first%>
            <% if @youtube_id != nil %>
              <iframe id="ytplayer" type="text/html" width="100%" height="350px" allowfullscreen style="border-radius:8px"
              src="http://www.youtube.com/embed/<%=@youtube_id.youtube_id%>?rel=0&amp;autoplay=1&mute=1"
              frameborder="0"></iframe>
            <% end %>
          </div>

        </div>
      </div>

      <div class="col-4 project-show-tokens-sticky p-4 border mt-3" data-controller="counter">
        <div class="artist-project-info-financial mb-15 align-items d-flex justify-content-between ">
          <div class="d-flex flex-column justify-content-evenly text-center bg-secondary border border-secondary rounded p-2 w-25">
            <p class="m-0 text-white h4 fw-bold">
            <span data-counter-target="price" class='d-none'><%= @project.unit_price.to_i %></span>
            <% if (@project.unit_price.to_i) >= 1000  %>
              <small>$</small><%=(@project.unit_price.to_i)/1000%>K</p>
            <% else  %>
              <small>$</small><%=(@project.unit_price.to_i) %>
            <% end %>
            <p class="m-0 text-white" style="font-size:12px">per token</p>
          </div>
          <div class="d-flex flex-column justify-content-evenly text-center border border-primary rounded p-2 ms-3 w-25">
            <p class="m-0 text-primary h4 fw-bold"><%= @project.number_of_tokens%></p>
            <p class="m-0" style="font-size:12px">tokens total</p>
          </div>
          <div class="d-flex flex-column justify-content-evenly text-center rounded p-2 ms-3 w-25" style="border:1px solid #f9bc0b">
            <p class="m-0 h4 fw-bold" style="color:#f9bc0b"><%= @project.number_of_transactions(@project) %></p>
            <p class="m-0" style="font-size:12px">tokens purchased</p>
          </div>
        </div>
        <!-- button for payment (stripe) -->
        <div class="align-items d-flex justify-content-between">
          <p>
          <%= form_tag carts_path(@cart), method: :post, class: "w-100" do %>
            <%#= hidden_field_tag 'token_id', @project.tokens.find { |token| token if !token.bought? }.id %>
            <%= hidden_field_tag 'project_id', @project.id %>
            <div class="input-group w-auto justify-content-center align-items-center my-4" >
              <input type="button" value="-" class="button-minus border rounded-circle icon-shape icon-sm mx-1 " data-action="click->counter#decrement" data-counter-target="minus">
              <input type="number" step="1" max="<%= @project.number_of_tokens - @project.number_of_transactions(@project)%>" min='0' value="0" class="quantity-field border-0 text-center w-25" data-counter-target="quantity" id="quantity" name="quantity">
              <input type="button" value="+" class="button-plus border rounded-circle icon-shape icon-sm " data-action="click->counter#increment" data-counter-target="plus" data-action="click->counter#quantity">
            </div>
            <p class='border-top text-center text-secondary pt-2'>Total $<span data-counter-target='subtotal' class='fw-bold fs-5'></span> </p>
            <%= button_tag(type: "submit", class: 'btn btn-secondary btn-token w-100 border-0') do %>
              Pay now <i class="fas fa-credit-card ms-2"></i>
            <% end %>
            <%# <%= submit_tag 'Pay now', class: 'btn btn-secondary btn-token w-100 border-0' class:"fas fa-credit-card"%>
          <% end %>
          </p>
        </div>
          <!-- project funding status -->
          <h5 class="text-primary m-0 mt-4 border-bottom"><i class="fas fa-coins text-secondary"></i>  Project funding status</h5>

          <div class="d-flex mt-3 mb-0 align-items-bottom" style="align-items: center;">
            <% amount_invested = @project.total_amount_invested(@project).to_i %>
            <p class="text-primary fw-bold fs-4 mb-0 me-2"><small>$</small><%= number_with_delimiter(amount_invested, :delimiter => ',') %>  </p>
            <p style="margin-bottom: 0;"><small>collected</small></p>
            <% total_amount_available = @project.total_amount_available(@project).to_i %>
            <%# <p class="mb-0">invested on <%= number_with_delimiter(total_amount_available, :delimiter => ',') $ goal</p> %>
          </div>
          <div class="progress my-3">
          <div class="progress-bar" role="progressbar" style="width: <%= (( @project.total_amount_invested(@project).to_f / @project.total_amount_available(@project).to_f) * 100).round %>%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><%= ((@project.total_amount_invested(@project).to_f / @project.total_amount_available(@project).to_f) * 100).round %>%</div>
          </div>
      </div>


      <!-- empty middle column -->

      <!-- project financial information: right part -->
      <div class="col col-lg-8 p-2 financial-information">
        <div class="p-2 col-lg-11 col-sm-12">


          <div class="project-show-invest">
            <!-- investment distribution  -->
            <div class="project-show-invest-left">
              <h5 class="text-primary mb-4 mt-3 border-bottom"><i class="fas fa-hand-holding-usd text-secondary"></i> Investment distribution</h5>
              <%= pie_chart @shares,
                legend: "right",
                colors: ["#6768AB", "#262161", "#f9bc0b"],
                suffix: '%',
                height: "200px",
                width: "400px",
                library: {legend: { labels: { font: { family: 'Comfortaa'} } } }
              %>
            </div>

            <!-- previsional information -->
            <div class="project-show-invest-right mt-5">
              <h5 class="text-primary my-4 border-bottom"><i class="fas fa-chart-line text-secondary"></i> Previsional information per year</h5>
              <div class="artist-project-info-financial justify-content-around">
                <div class="text-center p-2">
                  <p class="m-0 text-secondary fw-bold fs-4"> <small>$</small><%= (@project.project_revenue(@project).round)/1000%>K</p>
                  <p class="m-0" style="font-size:16px">estimated annual revenue</p>
                </div>
                <div class="text-center p-2 ms-3">
                  <p class="m-0 text-primary fw-bold fs-4"><%= number_with_delimiter(@project.expected_audio_streams_year/1000, :delimiter => ',')%>K</p>
                  <p class="m-0" style="font-size:16px">audio streams</p>
                </div>
                <div class="text-center p-2 ms-3">
                  <p class="m-0 fw-bold fs-4" style="color:#f9bc0b"><%= number_with_delimiter(@project.expected_video_streams_year/1000, :delimiter => ',')%>K</p>
                  <p class="m-0" style="font-size:16px;">video streams</p>
                </div>
              </div>
            </div>
          <!-- other information -->
            <h5 class="text-primary my-4 border-bottom col-12 mt-5"><i class="fas fa-info-circle text-secondary"></i> Other information</h5>
            <div class = "d-flex justify-content-between px-4 mb-5">
              <p class="text-secondary"> <strong>Release date:</strong> <%= @project.release_date.strftime("%B %d, %Y") %></p>
              <p class="text-secondary"> <strong>Distributor:</strong> <%= @project.distributor %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>