config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'carts/create'
  # get 'carts/show'
  # get 'dashboard/show'
  # get 'products/show'
  # get 'products/new'
  # get 'products/edit'
  # get 'products/update'
  # get 'products/create'
  # get 'projects/index'
  # get 'projects/new'
  # get 'projects/edit'
  # get 'projects/create'
  # get 'projects/update'
  # get 'projects/show'

  devise_for :users
  post 'create_playlist', to: 'dashboards#create_playlist'
  get '/auth/spotify/callback', to: 'dashboards#create_playlist'
  root to: 'pages#home'
  resources :projects, only: [:index, :show, :edit, :new, :create, :update] do
    resources :products, only: [:show, :new, :create]
    resources :transactions, only: [:new,:show, :create]
  end
  resource :dashboard, only: [:show]
  resources :carts, only: [:show, :create]
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
# needed so that the user never see its ID in the url
# dashboards controller need to be plural even though the route dashboard is singular
  def show
    @user = current_user
    authorize(:dashboard, :show?)

    projects = @user.transactions.group_by{ |t| t.token.project.name}
    @project_informations = []

    projects.each do |project_name, transactions|
      project = { project_name: project_name, transactions: transactions.count }
      @project_informations << project
    end
  end

  def create_playlist
    auth = request.env['omniauth.auth']
    authorize(:dashboard, :create_playlist?)

    current_user.token = auth.credentials.token
    current_user.uid = auth.uid
    current_user.save

    CreateSpotifyPlaylistService.new(current_user).call

    flash[:notice] = "Playlist added with success"
    redirect_to dashboard_path
  end
end

app/views/dashboards/_info.html.erb
<div class ="container">
  <%= user.first_name %>
</div>

app/views/dashboards/_project.html.erb
<div class="container">
<%= link_to "Add new project 😉", new_project_path, class:"btn btn-primary my-5" %>
  <% if current_user.projects.present? %>
    <div class="container">
    <div class="financial-info justify-content-center mb-5">
    <% current_user.projects.each do |project|  %>
      <%# financial results card per project %>
      <div class ="dashboard-artist-project border d-flex">
        <h3 class="dashboard-artist-project-name font-weight-bold text-dark mt-3" >
          <strong><%= project.name %></strong>
        </h3>

        <%# retrieving metrics %>
        <% token = Token.find_by(project_id: project.id) %>
        <% transactions = Transaction.where(token_id: token).count %>
        <% total_amount_invested = transactions * token.price %>
        <% total_amount_available = (project.number_of_tokens) * (token.price) %>

        <%# beg-higher part of the card %>
        <div class="dashboard-artist-project-high-part">

          <div class="dashboard-artist-project-high-part-left">
            <%# project photo %>
            <div class="photo-project-info-financial mb-2">
                <%= cl_image_tag project.photo.key, height: 200, width: 200, crop: :fill  %>
            </div>

            <div class="dashboard-artist-project-info">
              <p> Release date: <%= project.release_date %></p>
              <p> Distributor: <%= project.distributor %></p>
            </div>
          </div>

          <%# revenue chart %>
          <div class="revenue-graph">
            <%= column_chart project.revenues.group_by_month(:date).sum(:revenue), xtitle: "Month", ytitle: "Revenue", colors: ["#6768AB"], thousands: ",", width: "500px", height: "300px"%>
          </div>

          <%# end-higher part of the card %>
        </div>

        <%# beg-downest part of the card %>
        <div class="dashboard-artist-project-down-part mb-4">

          <div class="dashboard-artist-project-down-part-left">
            <%# revenue generated since beginning %>
            <div class="project-generated-revenue">
              <div class="project-generated-revenue-dollar fw-bold"> BALANCE </div>
              <div class="project-generated-revenue-increase"><%= image_tag "increase.png", height: 33, width: 33 %></div>
              <h2 class="text-white"><strong><%= number_with_delimiter((project.project_revenue(project).round), :delimiter => ',')%>$</strong></h2>
            </div>
          </div>

          <div class="dashboard-artist-project-down-part-right">
            <%# progress bar %>
            <div class="d-flex mt-3 mb-0 align-items-center text-dark">
              <p class="text-primary fw-bold fs-4 mb-0 me-2"><%= number_with_delimiter((project.total_amount_invested(project).to_i), :delimiter => ',') %>$</p>
              <p class="mb-0">invested on <%= number_with_delimiter((project.total_amount_available(project).to_i), :delimiter => ',')%> $ goal</p>
            </div>
            <div class="dashboard-progress mb-3">
              <div class="progress-bar" role="progressbar" style="width: <%= ((total_amount_invested.to_f / total_amount_available.to_f) * 100).round %>%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><%= ((total_amount_invested.to_f / total_amount_available.to_f) * 100).round %>%</div>
            </div>
            <%# progress bar-end %>

            <%# tokens info %>
            <div class="artist-project-info-financial">
              <div class="text-center bg-secondary border border-secondary rounded p-2 w-25">
                <p class="m-0 text-white fw-bold fs-5"><%= number_with_delimiter(token.price, :delimiter => ',')%> $</p>
                <p class="m-0 text-white" style="font-size:12px">per token</p>
              </div>
              <div class="text-center border border-primary rounded p-2 ms-3 w-25">
                <p class="m-0 text-primary fw-bold fs-5"><%= project.number_of_tokens%></p>
                <p class="m-0" style="font-size:12px">tokens total</p>
              </div>
              <div class="text-center rounded p-2 ms-3 w-25" style="border:1px solid #f9bc0b">
                <p class="m-0 fw-bold fs-5" style="color:#f9bc0b"><%= project.number_of_transactions(project) %></p>
                <p class="m-0" style="font-size:12px">tokens purchased</p>
              </div>
    
            </div>
            <%# tokens info-end %>
          </div>

          </div>
          </div>
          <%# beg-downest part of the card %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No projects yet !</p>
    <div class="height-100"></div>
  <% end %>
</div>

app/views/dashboards/_token.html.erb
<div class ="container">
  <% if current_user.tokens.empty? %>
    <p> No token yet ! </p>
    <%= link_to "Find investments 😉", projects_path, class:"btn btn-primary mb-5" %>
  <% else %>
    <!-- div with chart and other porfolio infos -->
    <div class="row align-items-center mb-2 align-items-start">
      <div class='col col-lg-7 py-3 px-3 bg-white'>
       <h5 class='mb-3 text-secondary'>Revenues per month per project</h5>

        <!-- drop down to select project -->
        <div data-controller="update-chart">
          <label for="project-select">Project:</label>
          <select id="project" data-action="change->update-chart#update">
            <% current_user.projects_as_investor.uniq.each do |p| %>
                <option value=<%= p.id %> data-chart-value=<%= current_user.revenues_as_investor.where(project_id: p.id).group_by_month(:date).sum('revenue * 0.001').to_a.to_json.html_safe%>><%= "#{User.find(p.user_id).artist_name} - #{p.name}" %></option>
            <% end %>
          </select>
        </div>

         <!-- chart -->
        <%= line_chart current_user.revenues_as_investor.where(project_id: current_user.projects_as_investor.first.id).group_by_month(:date, format: "%b %Y").sum('revenue * 0.001'), id: 'chart-projects-revenues', height: "250px", thousands: ",", colors: ["#262161"], suffix: ' $' %>
      </div>

      <div class='col col-lg-1'>
      </div>

      <!-- portfolio informations (tokens + amount invested) -->
      <div class='col col-lg-4'>
        <h5 class='mb-3 text-secondary'>Overview</h5>
        <div class='py-2 rounded p-3 bg-primary'>
          <p class='text-primary fs-4 mb-0 text-white'><%= current_user.number_of_token_user %></p>
          <p class='fs-6 my-0 text-white fw-light'>Tokens</p>
        </div>
        <div class='py-2 rounded p-3 bg-secondary my-3'>
          <p class='text-primary fs-4 mb-0 text-white'><%= number_with_delimiter(current_user.total_amount_invested_user , :delimiter => ',')%> $</p>
          <p class='fs-6 my-0 text-white fw-light'>Total amount invested</p>
        </div>
        <div class='py-2 rounded p-3' style='background-color:#f9bc0b'>
          <p class='fs-4 mb-0'><%= number_with_delimiter(current_user.revenues_as_investor.sum('revenue * 0.001').round(2), :delimiter => ',')%> $</p>
          <p class='fs-6 my-0 fw-light'>Total revenue</p>
        </div>
      </div>
    </div>

    <h5 class='text-secondary mt-5 mb-3'>My investments</h5>

    <%= form_tag '/auth/spotify', method: :post do %>
      <%= submit_tag "Create a Spotify playlist", class: "btn btn-primary mb-2", data: { disable_with: "Creating playlist..." } %>
    <% end %>

    <!-- list of projects -->
    <% @project_informations.each do |project_information| %>
      <div class="row align-items-center mb-2 bg-white py-1 rounded">
        <div class='col col-lg-1'>
          <%= cl_image_tag Project.find_by(name:project_information[:project_name]).photo.key, height: 100, width:100, crop: :fill, class: 'rounded' %>
        </div>
        <div class='col col-lg-2 ms-4'>
          <p class='mb-0 text-primary fw-bold'><%= link_to project_information[:project_name].upcase, project_path(Project.find_by(name:project_information[:project_name])), class:"text-decoration-none" %></p>
          <p class='mb-0 text-muted'>project name</p>
        </div>
        <div class='col col-lg-2'>
          <p class='mb-0 text-primary fw-bold'><%= User.find(Project.find_by(name:project_information[:project_name]).user_id).artist_name %></p>
          <p class='mb-0 text-muted'>artist</p>
        </div>
        <div class='col col-lg-3'>
          <p class='mb-0 text-primary fw-bold'><%= project_information[:transactions] %></p>
          <p class='mb-0 text-muted'>number of transactions</p>
        </div>
        <div class='col col-lg-3'>
          <p class='mb-0 text-primary fw-bold'><%= number_with_delimiter((Token.find_by(project_id: Project.find_by(name: project_information[:project_name])).price) * project_information[:transactions], :delimiter => ',') %>$</p>
          <p class='mb-0 text-muted'>amount invested</p>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="mb-5"></div>
</div>

app/views/dashboards/show.html.erb
<div class="container-gys">
  <div>
    <h1 class="my-5 text-primary">Welcome to your dashboard, <span class="banner-highlight-primary"><%=@user.first_name%></span>.</h1>
    <%# better to have partials so that several developers can work on the same page without conflicts %>
    <p>Your dashboard was last updated on <%= Time.current.to_formatted_s(:short)%> </p>
    <%# user: is from the partial, it's linked with current urrent in dashboard controller, all thanks to devise %>
    <%# <%= render "info", user: @user %>
  </div>

  <nav class="mt-4">
    <div class="nav nav-tabs mt-3" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="true">My portfolio</button>
      <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="false">My projects</button>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <%= render "token", user: @user %>
    </div>
    <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <%= render 'project' %>
    </div>
  </div>
</div>